import { StyleSheet } from "react-native";

export const iconStyles = StyleSheet.create({
  addIcon: {
    width: 16,
    height: 16,
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
  },
  addHorizontal: {
    position: "absolute",
    width: 12,
    height: 2,
    backgroundColor: "#000",
  },
  addVertical: {
    position: "absolute",
    width: 2,
    height: 12,
    backgroundColor: "#000",
  },
  closeIcon: {
    width: 12,
    height: 12,
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
  },
  closeLine1: {
    position: "absolute",
    width: 12,
    height: 2,
    backgroundColor: "#000",
    transform: [{ rotate: "45deg" }],
  },
  closeLine2: {
    position: "absolute",
    width: 12,
    height: 2,
    backgroundColor: "#000",
    transform: [{ rotate: "-45deg" }],
  },
});

export const windowStyles = StyleSheet.create({
  fullContent: {
    flex: 1,
    padding: 16,
    backgroundColor: "#c0c0c0",
  },
  fullTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 4,
    color: "#000",
    fontFamily: "MS Sans Serif, System",
  },
  fullSubtitle: {
    fontSize: 14,
    color: "#666",
    marginBottom: 20,
    fontFamily: "MS Sans Serif, System",
    alignSelf: "center",
  },
  imagePreview: {
    alignItems: "center",
    marginBottom: 20,
    position: "relative",
    alignSelf: "center",
  },
  previewImagePlaceholder: {
    width: 120,
    height: 120,
    borderWidth: 2,
    borderColor: "#000",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
    opacity: 0.2,
  },
  placeholderText: {
    position: "absolute",
    top: "50%",
    fontSize: 10,
    color: "#000",
    fontFamily: "MS Sans Serif, System",
    textAlign: "center",
  },
  previewImage: {
    width: 120,
    height: 120,
    borderWidth: 2,
    borderColor: "#000",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
  },
  removeImageButton: {
    position: "absolute",
    top: -8,
    right: -8,
    backgroundColor: "#c0c0c0",
    width: 20,
    height: 20,
    borderWidth: 1,
    borderColor: "#808080",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    justifyContent: "center",
    alignItems: "center",
  },
  uploadSection: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 8,
    color: "#000",
    fontFamily: "MS Sans Serif, System",
  },
  uploadOptions: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 20,
  },
  uploadButton: {
    flex: 1,
    alignItems: "center",
    padding: 12,
    backgroundColor: "#c0c0c0",
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
    minHeight: 70,
  },
  uploadIcon: {
    width: 40,
    height: 40,
    marginBottom: 6,
  },
  uploadText: {
    fontSize: 11,
    textAlign: "center",
    fontWeight: "bold",
    fontFamily: "MS Sans Serif, System",
  },
  formSection: {
    marginBottom: 20,
  },
  nameInputContainer: {
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#808080",
    borderLeftColor: "#808080",
    borderRightColor: "#ffffff",
    borderBottomColor: "#ffffff",
    backgroundColor: "white",
    paddingHorizontal: 6,
    paddingVertical: 4,
    minHeight: 24,
  },
  nameInput: {
    fontSize: 12,
    color: "#000000",
    fontFamily: "MS Sans Serif, System",
    padding: 0,
    margin: 0,
  },
  categoryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  categoryOption: {
    flex: 1,
    minWidth: "10%",
    alignItems: "center",
    padding: 8,
    backgroundColor: "#c0c0c0",
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 0,
    elevation: 3,
  },
  categoryOptionSelected: {
    borderColor: "#ff66b2",
    borderTopColor: "#808080",
    borderLeftColor: "#808080",
    borderRightColor: "#ffffff",
    borderBottomColor: "#ffffff",
    shadowOffset: { width: 1, height: 1 },
    elevation: 1,
  },
  categoryIcon: {
    width: 40,
    height: 40,
    marginBottom: 4,
  },
  categoryText: {
    fontSize: 10,
    fontWeight: "bold",
    textAlign: "center",
    fontFamily: "MS Sans Serif, System",
  },
  tipIcon: {
    width: 16,
    height: 16,
    marginRight: 8,
    marginTop: 1,
  },
  tipContent: {
    flex: 1,
  },
  tipTitle: {
    fontSize: 12,
    fontWeight: "bold",
    marginBottom: 2,
    color: "#000",
    fontFamily: "MS Sans Serif, System",
  },
  tipText: {
    fontSize: 10,
    color: "#000",
    lineHeight: 12,
    fontFamily: "MS Sans Serif, System",
  },
  actionBar: {
    marginTop: "auto",
  },
  actionButton: {
    backgroundColor: "#c0c0c0",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  actionButtonDisabled: {
    opacity: 0.6,
  },
  actionText: {
    color: "#000",
    fontWeight: "bold",
    fontSize: 12,
    fontFamily: "MS Sans Serif, System",
  },
  cameraOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    zIndex: 1000,
    justifyContent: "center",
    alignItems: "center",
  },
  cameraContainer: {
    backgroundColor: "#c0c0c0",
    padding: 20,
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
    width: "80%",
    maxWidth: 400,
  },
  cameraTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 16,
    textAlign: "center",
    fontFamily: "MS Sans Serif, System",
  },
  cameraPreview: {
    width: "100%",
    height: 300,
    backgroundColor: "#000",
    marginBottom: 16,
    borderWidth: 2,
    borderColor: "#000",
  },
  cameraControls: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  cameraButton: {
    backgroundColor: "#c0c0c0",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
  },
  cameraButtonText: {
    fontSize: 14,
    fontWeight: "bold",
    fontFamily: "MS Sans Serif, System",
  },
  tipAndBgRemoveRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 20,
  },
  tipBox: {
    flex: 1,
    backgroundColor: "#ffffcc",
    borderWidth: 1,
    borderColor: "#000",
    padding: 12,
    minHeight: 60,
  },
  bgRemoveButton: {
    backgroundColor: "#c0c0c0",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
    minWidth: 100,
    flexShrink: 0,
  },
  bgRemoveContent: {
    alignItems: "center",
    justifyContent: "center",
  },
  bgRemoveIcon: {
    width: 40,
    height: 40,
    marginBottom: 4,
  },
  bgRemoveText: {
    color: "#000",
    fontWeight: "bold",
    fontSize: 10,
    fontFamily: "MS Sans Serif, System",
    textAlign: "center",
  },
  bgRemoveButtonDisabled: {
    opacity: 0.6,
    backgroundColor: "#e0e0e0",
  },
});
