import { StyleSheet } from "react-native";

export const windowStyles = StyleSheet.create({
  desktopToolbar: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 16,
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  mobileToolbar: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 12,
    paddingHorizontal: 8,
  },
  toolbarButton: {
    backgroundColor: "#c0c0c0",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
    alignItems: "center",
    minWidth: 100,
  },
  toolbarButtonContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  toolbarIcon: {
    width: 20,
    height: 20,
  },
  toolbarText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#000",
    textAlign: "center",
  },
  pinkButton: {
    backgroundColor: "#CB78A3FFFF",
    borderColor: "#ff3385",
    borderTopColor: "#ff99cc",
    borderLeftColor: "#ff99cc",
    borderRightColor: "#e60073",
    borderBottomColor: "#e60073",
  },
  mobileCanvasSection: {
    flex: 2,
    backgroundColor: "#c0c0c0",
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
    padding: 8,
    marginBottom: 12,
  },
  fullContent: {
    flex: 1,
    padding: 16,
    backgroundColor: "#c0c0c0",
  },
  fullTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 4,
    color: "#000",
  },
  fullSubtitle: {
    fontSize: 14,
    color: "#666",
    marginBottom: 20,
    textAlign: "center",
  },
  mainLayout: {
    flex: 1,
    flexDirection: "row",
    gap: 16,
  },
  canvasSection: {
    flex: 2,
    backgroundColor: "#c0c0c0",
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
    padding: 12,
  },
  rightSection: {
    flex: 1,
    gap: 16,
    minWidth: 280,
  },
  wardrobeSection: {
    flex: 1,
    backgroundColor: "#c0c0c0",
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
    padding: 12,
    minHeight: 300,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000",
    marginBottom: 8,
  },
  canvas: {
    flex: 1,
    backgroundColor: "transparent",
    position: "relative",
    minHeight: 400,
  },
  canvasBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#000",
  },
  canvasItem: {
    position: "absolute",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  canvasItemImage: {
    borderRadius: 4,
  },
  removeItemButton: {
    position: "absolute",
    top: -8,
    right: -8,
    backgroundColor: "#ff4444",
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#000",
  },
  removeItemText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 14,
    lineHeight: 16,
  },
  resizeControls: {
    position: "absolute",
    bottom: -30,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  resizeButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#333",
  },
  increaseButton: {
    backgroundColor: "#4CAF50",
  },
  decreaseButton: {
    backgroundColor: "#f44336",
  },
  resizeButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 12,
  },
  emptyCanvas: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  emptyCanvasIcon: {
    width: 64,
    height: 64,
    marginBottom: 16,
    opacity: 0.5,
  },
  emptyCanvasText: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
  },
  categoryScroll: {
    marginBottom: 12,
    maxHeight: 80,
  },
  categoryButton: {
    alignItems: "center",
    padding: 8,
    backgroundColor: "#c0c0c0",
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
    marginRight: 8,
    minWidth: 70,
  },
  categoryButtonSelected: {
    borderColor: "#000",
    backgroundColor: "#ffffcc",
  },
  categoryIcon: {
    width: 32,
    height: 32,
    marginBottom: 4,
  },
  categoryText: {
    fontSize: 10,
    fontWeight: "bold",
    textAlign: "center",
  },
  itemsGrid: {
    flex: 1,
  },
  wardrobeItem: {
    alignItems: "center",
    padding: 8,
    backgroundColor: "#c0c0c0",
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
    marginBottom: 8,
  },
  wardrobeItemImage: {
    width: 60,
    height: 60,
    marginBottom: 4,
  },
  wardrobeItemName: {
    fontSize: 10,
    textAlign: "center",
    color: "#000",
    maxWidth: 80,
  },
  emptyWardrobe: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  emptyWardrobeText: {
    fontSize: 12,
    color: "#666",
    textAlign: "center",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 8,
    width: "80%",
    maxWidth: 400,
    borderWidth: 2,
    borderColor: "#c0c0c0",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
  },
  colorModalContent: {
    maxWidth: 500,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
    textAlign: "center",
  },
  modalText: {
    fontSize: 14,
    marginBottom: 15,
    textAlign: "center",
    color: "#333",
  },
  nameInputContainer: {
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#808080",
    borderLeftColor: "#808080",
    borderRightColor: "#ffffff",
    borderBottomColor: "#ffffff",
    backgroundColor: "white",
    paddingHorizontal: 8,
    paddingVertical: 6,
    marginBottom: 15,
  },
  nameInput: {
    fontSize: 14,
    color: "#000000",
    padding: 0,
    margin: 0,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 4,
    alignItems: "center",
  },
  cancelButton: {
    backgroundColor: "#c0c0c0",
    borderWidth: 2,
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
  },
  saveButton: {
    backgroundColor: "#ffffcc",
    borderWidth: 2,
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
  },
  cancelButtonText: {
    color: "#000",
    fontWeight: "bold",
  },
  saveButtonText: {
    color: "#000",
    fontWeight: "bold",
  },
  colorGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 8,
    marginBottom: 15,
  },
  colorOption: {
    width: 40,
    height: 40,
    borderWidth: 2,
    borderColor: "#000",
  },
  colorOptionSelected: {
    borderWidth: 4,
    borderColor: "#ff0000",
  },
  mobileFullContent: {
    flex: 1,
    padding: 12,
    backgroundColor: "#c0c0c0",
  },
  mobileCanvas: {
    flex: 1,
    backgroundColor: "transparent",
    position: "relative",
    minHeight: 300,
  },
  mobileBottomSection: {
    flex: 1,
    backgroundColor: "#c0c0c0",
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
    padding: 8,
  },
  mobileCategoryScroll: {
    marginBottom: 8,
    maxHeight: 60,
  },
  mobileCategoryButton: {
    alignItems: "center",
    padding: 6,
    backgroundColor: "#c0c0c0",
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
    marginRight: 6,
    minWidth: 60,
  },
  mobileCategoryIcon: {
    width: 24,
    height: 24,
    marginBottom: 2,
  },
  mobileCategoryText: {
    fontSize: 8,
    fontWeight: "bold",
    textAlign: "center",
  },
  mobileItemsGrid: {
    flex: 1,
  },
  mobileWardrobeItem: {
    alignItems: "center",
    padding: 6,
    backgroundColor: "#c0c0c0",
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
    marginBottom: 6,
    marginRight: 6,
    width: 70,
  },
  mobileWardrobeItemImage: {
    width: 40,
    height: 40,
    marginBottom: 2,
  },
  mobileWardrobeItemName: {
    fontSize: 8,
    textAlign: "center",
    color: "#000",
    maxWidth: 60,
  },
});
