import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  fullContent: {
    flex: 1,
    padding: 16,
    backgroundColor: "#c0c0c0",
  },
  header: {
    marginBottom: 16,
  },
  subtitle: {
    fontSize: 14,
    color: "#666",
    marginBottom: 12,
  },
  controls: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  controlButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#c0c0c0",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
    gap: 6,
  },
  dressModeActive: {
    backgroundColor: "#ff66b2",
    borderColor: "#ff3385",
    borderTopColor: "#ff99cc",
    borderLeftColor: "#ff99cc",
    borderRightColor: "#e60073",
    borderBottomColor: "#e60073",
  },
  controlIcon: {
    width: 16,
    height: 16,
  },
  controlButtonText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#000",
  },
  categoriesLayout: {
    flex: 1,
    flexDirection: "row",
    gap: 12,
  },
  leftColumn: {
    flex: 2,
    gap: 12,
  },
  rightColumn: {
    flex: 1,
    gap: 12,
  },
  categorySection: {
    backgroundColor: "#c0c0c0",
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
    padding: 12,
  },
  categoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    gap: 8,
  },
  categoryIcon: {
    width: 20,
    height: 20,
  },
  categoryTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000",
  },
  itemsContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  arrowButton: {
    backgroundColor: "#c0c0c0",
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#dfdfdf",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
  },
  arrowText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#000",
  },
  itemDisplay: {
    flex: 1,
    alignItems: "center",
    marginHorizontal: 3,
  },
  dressItemDisplay: {},
  itemImage: {
    marginBottom: 8,
  },
  placeholderImage: {
    backgroundColor: "#e0e0e0",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 8,
  },
  placeholderText: {
    fontSize: 12,
    color: "#666",
  },
  itemsCount: {
    fontSize: 10,
    color: "#666",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 8,
    width: "80%",
    maxWidth: 400,
    borderWidth: 2,
    borderColor: "#c0c0c0",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
    gap: 8,
  },
  modalIcon: {
    width: 20,
    height: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
  },
  modalText: {
    fontSize: 14,
    marginBottom: 15,
    textAlign: "center",
    color: "#333",
    lineHeight: 18,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 4,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
  },
  cancelButton: {
    backgroundColor: "#c0c0c0",
    borderWidth: 2,
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
  },
  favoriteButton: {
    backgroundColor: "#ffcccc",
    borderWidth: 2,
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
  },
  cancelButtonText: {
    color: "#000",
    fontWeight: "bold",
  },
  favoriteButtonText: {
    color: "#000",
    fontWeight: "bold",
  },
  buttonIcon: {
    width: 16,
    height: 16,
  },
});
