import { StyleSheet } from "react-native";

export const resizeStyles = StyleSheet.create({
  resizeControls: {
    position: "absolute",
    top: -30,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  resizeButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: "#333",
  },
  increaseButton: {
    backgroundColor: "#4CAF50",
  },
  decreaseButton: {
    backgroundColor: "#f44336",
  },
  resizeButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 14,
    lineHeight: 18,
  },
});

export const windowStyles = StyleSheet.create({
  fullContent: {
    flex: 1,
    padding: 16,
    backgroundColor: "transparent",
  },
  fullSubtitle: {
    fontSize: 14,
    color: "#666",
    marginBottom: 10,
    textAlign: "center",
  },
  roomLayout: {
    flex: 1,
    position: "relative",
  },
  furnitureRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 10,
    height: 150,
    paddingHorizontal: 10,
    marginTop: 10,
  },
  furnitureRowMobile: {
    height: 120,
    marginBottom: 5,
    paddingHorizontal: 5,
  },
  furnitureImage: {
    resizeMode: "contain",
  },
  wardrobeSize: {
    width: 180,
    height: 160,
  },
  wardrobeSizeMobile: {
    width: 140,
    height: 120,
  },
  jewelryBoxSize: {
    width: 100,
    height: 80,
  },
  jewelryBoxSizeMobile: {
    width: 80,
    height: 60,
  },
  hangerSize: {
    width: 130,
    height: 100,
  },
  hangerSizeMobile: {
    width: 100,
    height: 80,
  },
  shoeShelfSize: {
    width: 90,
    height: 70,
  },
  shoeShelfSizeMobile: {
    width: 70,
    height: 50,
  },
  floorArea: {
    flex: 1,
    backgroundColor: "transparent",
    marginTop: 10,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#e0e0e0",
    minHeight: 300,
  },
  floorAreaMobile: {
    minHeight: 250,
    marginTop: 5,
  },
  floorTexture: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    height: "100%",
    opacity: 0.3,
  },
  draggableItem: {
    position: "absolute",
    alignItems: "center",
    padding: 0,
    backgroundColor: "transparent",
    borderRadius: 0,
    borderWidth: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 3,
    zIndex: 10,
  },
  itemImage: {
    borderRadius: 0,
    backgroundColor: "transparent",
  },
  emptyFloor: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  emptyText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#666",
    marginBottom: 4,
  },
  emptySubtext: {
    fontSize: 12,
    color: "#666",
    textAlign: "center",
  },
  trashBin: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "transparent",
    borderRadius: 0,
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
  },
  trashBinIcon: {
    width: 40,
    height: 40,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 8,
    width: "80%",
    maxWidth: 300,
    borderWidth: 2,
    borderColor: "#c0c0c0",
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
  },
  modalContentMobile: {
    width: "90%",
    marginHorizontal: 20,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
    textAlign: "center",
  },
  modalText: {
    fontSize: 14,
    marginBottom: 20,
    textAlign: "center",
    color: "#333",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 4,
    alignItems: "center",
  },
  cancelButton: {
    backgroundColor: "#c0c0c0",
    borderWidth: 2,
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
  },
  deleteButton: {
    backgroundColor: "#ff4444",
    borderWidth: 2,
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#cc0000",
    borderBottomColor: "#cc0000",
  },
  cancelButtonText: {
    color: "#000",
    fontWeight: "bold",
  },
  deleteButtonText: {
    color: "white",
    fontWeight: "bold",
  },
});

export const styles = StyleSheet.create({
  furnitureView: {
    flex: 1,
    padding: 16,
    backgroundColor: "transparent",
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#ccc",
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  backButton: {
    backgroundColor: "#c0c0c0",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 4,
    borderWidth: 2,
    borderTopColor: "#ffffff",
    borderLeftColor: "#ffffff",
    borderRightColor: "#808080",
    borderBottomColor: "#808080",
  },
  backButtonText: {
    color: "#000",
    fontWeight: "bold",
    fontSize: 12,
  },
  viewTitle: {
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    color: "#333",
  },
  placeholder: {
    width: 60,
  },
  furnitureBackground: {
    width: "100%",
    height: "100%",
    position: "absolute",
    resizeMode: "contain",
  },
  hangerRackImage: {
    width: "100%",
    height: "100%",
    position: "relative",
    resizeMode: "contain",
  },
  furnitureInterior: {
    flex: 1,
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 200,
  },
  furnitureItemImage: {
    backgroundColor: "transparent",
  },
});
